language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: tmb10dAWwYcVDzaNxSa+0T7OGu+BSTGoknqA3jyqTUpGlZ4kiweoEjbtHOdCLFQ3+PzwqZpcJhJoIS3i5eB/gOXAeo1gl2t8EYTNgdN2VF5u7GoZvE9QcC4PsdO61giWirzFXPFgim+EdRTPH+/QXB1h0lOAc+bOxZ22IGR7JS8Pt3tYGl7ueivoW+/0jKnY1pf7Ep5AafpxGp1PbHP4j76jKfHhz8EeSvVtQD7NMrh0nsbRZQETjPiGuyLvzy1nPHzkyzr1CyeG9xLSFninG1OArvulJgZonZsFQtsTZFqSxPVML9bRHvc8AwY2M1U5W1aWxRbBM0M2KaJEBWctc8S9y8uLOwm+jkaDSiQLCMvCsR7Eh+9DpQbsiv6CjDgCqELLO18m8038QyQZ2V0p11yJL5G3RsS4JkK9NQxU1MTkqlVLfbIw/0Z4l/Z4xntZpsZCT8V1j7fJAf8oqy/VpXfPwAaoYHO3zpVxJTGpAHMX9Lbi7AdH1NiDZj52qzq5h8rWKCD6DUtLkLfFskUIFBnaVBbhWFubc4YS8407pgQBYxvuFoUs2mbys3mJOEqDBMxzMf+US822JiYNS+nm7qw9mkSx+8yoaP8qBJ4KdrtaEPJ/EO5iaXQ3zHPbMn8dvqRJoGwN9O8KLmi+MsbDiOKfgv/OzU8Q2sjfr4uCL+A=
  app: thawing-ravine-45117