language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: lm8Y1+OySMx9V7LFu5JCWDdQWknm8Xvc2olQ9YyaGI6DtwcdDNsF+J9Sol/SvnBCYegK7eOhXfRRJIMa9PmtropzYeHzbWfSHTW/AqwyV3OYVKzMZJpGs/RxcnfV/IvfD9qJbKRla6Dpo552/dBLpKhx6HdH6B69rduz7UL+cFFyLiw3mC3H37Uyq8q2x90CFtMshcxRjuuOXtmM8mdbztKuuAqwJ8ZC68v6BNzhYUujTH/kC8dAhN3EWQalYq70ZI19FHV7q+vJyxWTFDtt6O8uiOXGQ8np/vcL5kKShs2Pfe44K0SaNygUGLhWTJzI9gKtJIWtynkQci0QLBDfZ7UIYshAeCxt1I1c4g0bCDk0ipyQEC3MzVm2yfTsCNzsz/g+EOJBS4OLzJXSs2NzfBEf9ATjll4RJjrjCgfaulN2qUtA3ILQ4M7j0z8WPKyHMgG8iLtbfTDTS47zE6r2KMV1s5XFGNkceHhBQu8Rn4WRjeiYKN98SyKVUQYSrjTtBfy1kGm2JGOmaB/KRf3NN3X/i3vmjqpzo17LA40ZfZfamkv6VhZjhwRGiPf7uDE4iXNldrlvVuL/+o/6zhgI6DpnTA+wecXqKvHutaw+toqGzLw3BRoJ3SO70eHzX1lFQqt10tvmUAWFqauaZiy/oOhk9aG0FG1+u+nts4OYcPk=
